name:                voxel-haskell
version:             0.1.0.0
license:             GPL-3

dependencies:
- base >= 4.7 && < 5
- tasty
- GLFW
- OpenGL
- mtl
- lens
- containers
- vector
- text

default-extensions:
- LambdaCase
- ViewPatterns
- FlexibleContexts
- MultiParamTypeClasses
- TemplateHaskell
- TupleSections

library:
  source-dirs: src

executables:
  voxel-haskell:
    source-dirs:         app
    main:                VoxelHaskell/Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - voxel-haskell

tests:
  voxel-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - voxel-haskell
