name:                voxel-haskell
version:             0.1.0.0
license:             GPL-3

dependencies:
- base >= 4.7 && < 5
- tasty

library:
  source-dirs: src

tests:
  voxel-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - voxel-haskell
