resolver: lts-13.19

packages:
- .

extra-deps:
- GLFW-0.5.2.5@sha256:fa54e997076a6b415c43100830e9b6ab6827c8766aef80e66d598de9b2400b93

nix:
  enable: true
  packages: [ freeglut x11 mesa xorg.libXext xorg.libXxf86vm xorg.libX11 libGL ]

ghc-options:
  "$locals": -fwarn-incomplete-patterns -fwarn-unused-imports
